### ISSUE TITLE
I2C to USB

### ISSUE THREAD

**Issue by Bra1nsen** [darton/BME280USB#1]
Could I connect the bme280 directly via usb to the pi 4?

![image](https://user-images.githubusercontent.com/58213050/167087381-15109614-98a8-4354-a583-8bfba2e95bd6.png)

**Comment by darton** [comment]
BME280 [i2c] <- 4 wire cable-> [i2C] Raspberry Pi Pico [USB] <-usb cable-> Raspberry Pi 4 [USB]

**Comment by Bra1nsen** [comment]
Why do i need pico ??

**Comment by darton** [comment]
If you want to use the BME280 sensor on the longest cable than the i2c standard allows.
